name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Customize this to match your branch

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@v3
    - name: build
      run: |
        docker build .-t binara1991/Github_docker:latest
    - name: pulish
      run: |
        docker login -u binara1991 -p ${{ secrets.DOCKER_GITHUB }}
        docker push binara1991/Github_docker:latest