version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    links:          # Moved the 'links' property here
      - db

  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Removed space before 'root'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

