name: Publish Docker Images to GHCR

on:
  push:
    branches: [ main, master ]  # Trigger the workflow on pushes to 'main' or 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image 1
        run: |
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .  
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Docker Build and Push
        run: echo "Build and push Docker image completed successfully"
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Adjust the path to your Dockerfile if needed
          push: true
          tags: binara1991/github_docker:latest  # Adjust the repository and tag as needed

